version: "3"
services:
  grafana:
    restart: unless-stopped
    build:
      context: .
    container_name: grafana
    ports:
      - 9000:3000
    volumes:
      - ./docker/grafana:/var/lib/grafana

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`test.yourdomain.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
    networks:
      - traefik
      
networks:
  traefik:
    external: true