version: "3"
services:
  grafana:
    restart: unless-stopped
    build:
      context: .
    container_name: grafana
    ports:
      - 9000:3000
    volumes:
      - ./docker/grafana:/var/lib/grafana