version: '3.3'
services:
  db:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'XD5CgskN'
      MYSQL_ROOT_PASSWORD: 'XD5CgskN'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql