- name: Add apache config
  hosts: all
  become: yes
  tasks:
    - name: Add apache config
      template:
        src: ../apache_conf/laravel.conf
        dest: /etc/apache2/sites-available/laravel.conf
      notify: Restart Apache Server
    - name: Enable mod_rewrite
      apache2_module:
        state: present
        name: rewrite
      notify: Restart Apache Server
    - name: Enable site
      apache2_module:
        state: present
        name: default
      notify: Restart Apache Server
    - name: Restart Apache Server
      service:
        name: apache2
        state: restarted